### ISSUE TITLE
스크립트에서 정점을 더할수 있는 기능이 필요합니다.

### ISSUE THREAD

**Issue by chromedays** [geniikw/SplineMeshDrawer-PatchNote#3]
for (int i = 0; i < 10; ++i)
{
    line.Add(new Point(...));
}

이런식으로 스크립트상에서 라인을 만들수 있는 기능이 필요한데 보이지 않네요. 제가 못찾은건지...

**Comment by geniikw** [comment]
답변이 늦어 죄송합니다.

그렇지 않아도 스크립트로 조작하는게 매우 어렵다고 생각해서

고치는 중입니다. ㅠㅠ 다음 주 월요일 정도까지 해 놓겠습니다 .

리뷰까지 따지면 화요일 정도에 업데이트 될 것 같습니다.

**Comment by geniikw** [comment]
draft로 제출했습니다. 혹시나 급하시면 메일이랑 포함에서 밑에 답글 달아주세요. 보내드릴께요.
